apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencrypt-disk
  namespace: letsencrypt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
    